# Generated by Django 4.2.1 on 2024-01-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_chave_pix_usuario_reputacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
