# Generated by Django 5.0 on 2024-01-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qtd_horas', models.IntegerField()),
                ('porcentagem_comissao', models.FloatField()),
            ],
        ),
    ]
